import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'remixicon/fonts/remixicon.css'; 
import { footerSections,contactInfo } from "../data/sliderData";

import Footer from '../components/Footer';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-inter',
 })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='mx-auto md:w-[1440px] h-screen'>

        {children}
        <Footer sections={footerSections} contactInfo={contactInfo}/>
        </div>
        </body>
    </html>
  )
}
